services:
  db:
    image: postgres:18.1-trixie
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: user
      DB_PASSWORD: securepassword123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: task_db
      DB_SSLMODE: disable
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"

  frontend:
    build: ./ui
    environment:
     BACKEND_URL: ${BACKEND_URL:-http://backend:8000}
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  postgres_data:
    name: tasks_data